In [1]:
import pandas as pd
import numpy as np
import math
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.metrics import r2_score,mean_squared_error

In [2]:
df = pd.read_excel("D:\BTP\Gopalkheda and yerli\cause effect model\cause-effect.xlsx")
df

Year  Month  Day  Discharge  cluster  RF101  RF117  RF80  cluster(t-1)  \
0      1977      6    1        0.3   0.0000    0.0    0.0   0.0        0.0000   
1      1977      6    2        0.3   0.0000    0.0    0.0   0.0        0.0000   
2      1977      6    3        0.3   0.0000    0.0    0.0   0.0        0.0000   
3      1977      6    4        0.3   0.0000    0.0    0.0   0.0        0.0000   
4      1977      6    5        0.3   0.0000    0.0    0.0   0.0        0.0000   
...     ...    ...  ...        ...      ...    ...    ...   ...           ...   
16066  2021      5   27        0.0   0.0083    0.0    0.0   0.0        0.0000   
16067  2021      5   28        0.0   0.0000    0.0    5.2   0.0        0.0083   
16068  2021      5   29        0.0   0.1713    0.4    0.0   0.0        0.0000   
16069  2021      5   30        0.0   1.0604    1.2    0.0   0.0        0.1713   
16070  2021      5   31        0.0   0.4888    0.4    0.0   0.2        1.0604   

       cluster(t-2)  cluster(t-3)  RF101(t-1)  RF101(t-2)  RF101(t-3)  \
0            0.0000        0.0000         0.0         0.0         0.0   
1            0.0000        0.0000         0.0         0.0         0.0   
2            0.0000        0.0000         0.0         0.0         0.0   
3            0.0000        0.0000         0.0         0.0         0.0   
4            0.0000        0.0000         0.0         0.0         0.0   
...             ...           ...         ...         ...         ...   
16066        0.0000        0.0000         0.0         0.0         0.0   
16067        0.0000        0.0000         0.0         0.0         0.0   
16068        0.0083        0.0000         0.0         0.0         0.0   
16069        0.0000        0.0083         0.4         0.0         0.0   
16070        0.1713        0.0000         1.2         0.4         0.0   

       RF117(t-1)  RF117(t-2)  RF117(t-3)  RF80(t-1)  RF80(t-2)  RF80(t-3)  
0             0.0         0.0         0.0        0.0        0.0        0.0  
1             0.0         0.0         0.0        0.0        0.0        0.0  
2             0.0         0.0         0.0        0.0        0.0        0.0  
3             0.0         0.0         0.0        0.0        0.0        0.0  
4             0.0         0.0         0.0        0.0        0.0        0.0  
...           ...         ...         ...        ...        ...        ...  
16066         0.0         0.0         0.0        0.0        0.0        0.0  
16067         0.0         0.0         0.0        0.0        0.0        0.0  
16068         5.2         0.0         0.0        0.0        0.0        0.0  
16069         0.0         5.2         0.0        0.0        0.0        0.0  
16070         0.0         0.0         5.2        0.0        0.0        0.0  

[16071 rows x 20 columns]

In [3]:
df1 = df[0:12418]
df2 = df[12418:]
df1

Year  Month  Day  Discharge  cluster  RF101  RF117  RF80  cluster(t-1)  \
0      1977      6    1        0.3      0.0    0.0    0.0   0.0           0.0   
1      1977      6    2        0.3      0.0    0.0    0.0   0.0           0.0   
2      1977      6    3        0.3      0.0    0.0    0.0   0.0           0.0   
3      1977      6    4        0.3      0.0    0.0    0.0   0.0           0.0   
4      1977      6    5        0.3      0.0    0.0    0.0   0.0           0.0   
...     ...    ...  ...        ...      ...    ...    ...   ...           ...   
12413  2011      5   27        0.0      0.0    0.0    0.0   0.0           0.0   
12414  2011      5   28        0.0      0.0    0.0    1.1   0.0           0.0   
12415  2011      5   29        0.0      0.0    0.0    0.0   0.0           0.0   
12416  2011      5   30        0.0      0.0    0.0    0.0   0.0           0.0   
12417  2011      5   31        0.0      0.0    0.0    0.0   0.0           0.0   

       cluster(t-2)  cluster(t-3)  RF101(t-1)  RF101(t-2)  RF101(t-3)  \
0               0.0           0.0         0.0         0.0         0.0   
1               0.0           0.0         0.0         0.0         0.0   
2               0.0           0.0         0.0         0.0         0.0   
3               0.0           0.0         0.0         0.0         0.0   
4               0.0           0.0         0.0         0.0         0.0   
...             ...           ...         ...         ...         ...   
12413           0.0           0.0         0.0         0.0         0.0   
12414           0.0           0.0         0.0         0.0         0.0   
12415           0.0           0.0         0.0         0.0         0.0   
12416           0.0           0.0         0.0         0.0         0.0   
12417           0.0           0.0         0.0         0.0         0.0   

       RF117(t-1)  RF117(t-2)  RF117(t-3)  RF80(t-1)  RF80(t-2)  RF80(t-3)  
0             0.0         0.0         0.0        0.0        0.0        0.0  
1             0.0         0.0         0.0        0.0        0.0        0.0  
2             0.0         0.0         0.0        0.0        0.0        0.0  
3             0.0         0.0         0.0        0.0        0.0        0.0  
4             0.0         0.0         0.0        0.0        0.0        0.0  
...           ...         ...         ...        ...        ...        ...  
12413         0.0         0.0         0.0        0.0        0.0        0.0  
12414         0.0         0.0         0.0        0.0        0.0        0.0  
12415         1.1         0.0         0.0        0.0        0.0        0.0  
12416         0.0         1.1         0.0        0.0        0.0        0.0  
12417         0.0         0.0         1.1        0.0        0.0        0.0  

[12418 rows x 20 columns]

In [4]:
df2

Year  Month  Day  Discharge  cluster  RF101  RF117  RF80  cluster(t-1)  \
12418  2011      6    1        0.0   0.0000    0.0    0.0   0.0        0.0000   
12419  2011      6    2        0.0   0.0735    0.0    0.0   0.0        0.0000   
12420  2011      6    3        0.0   0.4980    0.0    4.9   0.9        0.0735   
12421  2011      6    4        0.0   0.0415    0.0    2.0   0.0        0.4980   
12422  2011      6    5        0.0   0.0000    0.0    0.0   0.0        0.0415   
...     ...    ...  ...        ...      ...    ...    ...   ...           ...   
16066  2021      5   27        0.0   0.0083    0.0    0.0   0.0        0.0000   
16067  2021      5   28        0.0   0.0000    0.0    5.2   0.0        0.0083   
16068  2021      5   29        0.0   0.1713    0.4    0.0   0.0        0.0000   
16069  2021      5   30        0.0   1.0604    1.2    0.0   0.0        0.1713   
16070  2021      5   31        0.0   0.4888    0.4    0.0   0.2        1.0604   

       cluster(t-2)  cluster(t-3)  RF101(t-1)  RF101(t-2)  RF101(t-3)  \
12418        0.0000        0.0000         0.0         0.0         0.0   
12419        0.0000        0.0000         0.0         0.0         0.0   
12420        0.0000        0.0000         0.0         0.0         0.0   
12421        0.0735        0.0000         0.0         0.0         0.0   
12422        0.4980        0.0735         0.0         0.0         0.0   
...             ...           ...         ...         ...         ...   
16066        0.0000        0.0000         0.0         0.0         0.0   
16067        0.0000        0.0000         0.0         0.0         0.0   
16068        0.0083        0.0000         0.0         0.0         0.0   
16069        0.0000        0.0083         0.4         0.0         0.0   
16070        0.1713        0.0000         1.2         0.4         0.0   

       RF117(t-1)  RF117(t-2)  RF117(t-3)  RF80(t-1)  RF80(t-2)  RF80(t-3)  
12418         0.0         0.0         0.0        0.0        0.0        0.0  
12419         0.0         0.0         0.0        0.0        0.0        0.0  
12420         0.0         0.0         0.0        0.0        0.0        0.0  
12421         4.9         0.0         0.0        0.9        0.0        0.0  
12422         2.0         4.9         0.0        0.0        0.9        0.0  
...           ...         ...         ...        ...        ...        ...  
16066         0.0         0.0         0.0        0.0        0.0        0.0  
16067         0.0         0.0         0.0        0.0        0.0        0.0  
16068         5.2         0.0         0.0        0.0        0.0        0.0  
16069         0.0         5.2         0.0        0.0        0.0        0.0  
16070         0.0         0.0         5.2        0.0        0.0        0.0  

[3653 rows x 20 columns]

In [5]:
r1 = linear_model.LinearRegression()
r1.fit(df1[["cluster"]],df1.Discharge)
predicted = r1.predict(df2[["cluster"]])
print(r1.coef_, r1.intercept_, r2_score(df2.Discharge, predicted), mean_squared_error(df2.Discharge, predicted,squared = False))

[37.49060613] 8.308946776907987 0.21034615365129006 145.20753281175618


In [6]:
r1 = linear_model.LinearRegression()
r1.fit(df1[["cluster","RF101"]],df1.Discharge)
predicted = r1.predict(df2[["cluster","RF101"]])
print(r1.coef_, r1.intercept_, r2_score(df2.Discharge, predicted), mean_squared_error(df2.Discharge, predicted,squared = False))

[32.77293342  1.22978381] 7.919909689002495 0.21035920700191446 145.20633263228444


In [7]:
r1 = linear_model.LinearRegression()
r1.fit(df1[["cluster(t-1)"]],df1.Discharge)
predicted = r1.predict(df2[["cluster(t-1)"]])
print(r1.coef_, r1.intercept_, r2_score(df2.Discharge, predicted), mean_squared_error(df2.Discharge, predicted,squared = False))

[41.58520454] 5.772552148353768 0.3266844225333866 134.08497026224353


In [8]:
r1 = linear_model.LinearRegression()
r1.fit(df1[["cluster(t-1)","RF101(t-1)","RF117(t-1)","RF80(t-1)"]],df1.Discharge)
predicted = r1.predict(df2[["cluster(t-1)","RF101(t-1)","RF117(t-1)","RF80(t-1)"]])
print(r1.coef_, r1.intercept_, r2_score(df2.Discharge, predicted), mean_squared_error(df2.Discharge, predicted,squared = False))

[23.51326018 -3.46998262  4.78028738  3.74164849] 2.2189300580805167 0.3589060750587193 130.8373079413951


In [9]:
r1 = linear_model.LinearRegression()
r1.fit(df1[["cluster","RF101(t-1)","RF117(t-1)","RF80(t-1)"]],df1.Discharge)
predicted = r1.predict(df2[["cluster","RF101(t-1)","RF117(t-1)","RF80(t-1)"]])
print(r1.coef_, r1.intercept_, r2_score(df2.Discharge, predicted), mean_squared_error(df2.Discharge, predicted,squared = False))

[21.10176511 -1.78308053  4.54165915  4.20753719] -1.1533510310223605 0.3828674529613858 128.3689516855596


In [10]:
r1 = linear_model.LinearRegression()
r1.fit(df1[["cluster","RF101(t-1)","RF117","RF80(t-1)"]],df1.Discharge)
predicted = r1.predict(df2[["cluster","RF101(t-1)","RF117","RF80(t-1)"]])
print(r1.coef_, r1.intercept_, r2_score(df2.Discharge, predicted), mean_squared_error(df2.Discharge, predicted,squared = False))

[20.4533475   1.71006124  0.81024051  5.03814052] -0.12536497956471138 0.39123831577213286 127.49537300624641


In [11]:
r1 = linear_model.LinearRegression()
r1.fit(df1[["cluster(t-1)","RF101(t-1)","RF117(t-1)","RF80"]],df1.Discharge)
predicted = r1.predict(df2[["cluster(t-1)","RF101(t-1)","RF117(t-1)","RF80"]])
print(r1.coef_, r1.intercept_, r2_score(df2.Discharge, predicted), mean_squared_error(df2.Discharge, predicted,squared = False))

[24.76852502 -2.21210421  4.6473855   3.79408968] -1.6418294756006944 0.384429071894993 128.20643363136318


In [12]:
r1 = linear_model.LinearRegression()
r1.fit(df1[["cluster(t-1)","RF101","RF117(t-1)","RF80(t-1)"]],df1.Discharge)
predicted = r1.predict(df2[["cluster(t-1)","RF101","RF117(t-1)","RF80(t-1)"]])
print(r1.coef_, r1.intercept_, r2_score(df2.Discharge, predicted), mean_squared_error(df2.Discharge, predicted,squared = False))

[18.96577027  2.78404922  2.37299747  2.2996458 ] -0.7061568246061611 0.4129626490767887 125.19980032082965


In [13]:
r1 = linear_model.LinearRegression()
r1.fit(df1[["cluster(t-2)","RF101(t-1)","RF117(t-1)","RF80(t-1)"]],df1.Discharge)
predicted = r1.predict(df2[["cluster(t-2)","RF101(t-1)","RF117(t-1)","RF80(t-1)"]])
print(r1.coef_, r1.intercept_, r2_score(df2.Discharge, predicted), mean_squared_error(df2.Discharge, predicted,squared = False))

[ 8.19112511 -2.21961825  5.4067782   5.3981566 ] 2.4586387238951346 0.3584356519866523 130.8853021581747


In [14]:
r1 = linear_model.LinearRegression()
r1.fit(df1[["cluster(t-2)","RF101","RF117(t-1)","RF80(t-1)"]],df1.Discharge)
predicted = r1.predict(df2[["cluster(t-2)","RF101","RF117(t-1)","RF80(t-1)"]])
print(r1.coef_, r1.intercept_, r2_score(df2.Discharge, predicted), mean_squared_error(df2.Discharge, predicted,squared = False))

[7.5752676  2.95774181 3.3440635  3.9570026 ] -1.110567372288898 0.4186935295496549 124.58717760708676


In [15]:
r1 = linear_model.LinearRegression()
r1.fit(df1[["cluster(t-2)","RF101(t-2)","RF117","RF80(t-1)"]],df1.Discharge)
predicted = r1.predict(df2[["cluster(t-2)","RF101(t-2)","RF117","RF80(t-1)"]])
print(r1.coef_, r1.intercept_, r2_score(df2.Discharge, predicted), mean_squared_error(df2.Discharge, predicted,squared = False))

[9.02179003 0.23885409 3.26475045 6.67575853] -0.7896558650928256 0.3723548070277837 129.45769568420133


In [16]:
r1 = linear_model.LinearRegression()
r1.fit(df1[["cluster(t-1)","cluster","RF101(t-2)","RF80(t-2)","RF117(t-1)","RF101","RF80"]],df1.Discharge)
predicted = r1.predict(df2[["cluster(t-1)","cluster","RF101(t-2)","RF80(t-2)","RF117(t-1)","RF101","RF80"]])
print(r1.coef_, r1.intercept_, r2_score(df2.Discharge, predicted), mean_squared_error(df2.Discharge, predicted,squared = False))

[17.85291777 17.04954041 -0.17310938  1.16596241  2.88372923 -0.31179841
  1.40245177] -4.043544131892581 0.4025607367680214 126.30415836971896


In [17]:
r1 = linear_model.LinearRegression()
r1.fit(df1[["cluster(t-1)","RF101","RF117(t-2)","RF80(t-1)","RF117(t-1)"]],df1.Discharge)
predicted = r1.predict(df2[["cluster(t-1)","RF101","RF117(t-2)","RF80(t-1)","RF117(t-1)"]])
print(r1.coef_, r1.intercept_, r2_score(df2.Discharge, predicted), mean_squared_error(df2.Discharge, predicted,squared = False))

[17.13334803  2.8095945   1.1443672   2.43659192  1.96876277] -2.33535764723387 0.42253853970929944 124.17445750076094


In [18]:
r1 = linear_model.LinearRegression()
r1.fit(df1[["cluster(t-1)","RF101(t-3)","RF117(t-1)","RF80(t-1)","RF117(t-1)","RF101(t-2)","cluster"]],df1.Discharge)
predicted = r1.predict(df2[["cluster(t-1)","RF101(t-3)","RF117(t-1)","RF80(t-1)","RF117(t-1)","RF101(t-2)","cluster"]])
print(r1.coef_, r1.intercept_, r2_score(df2.Discharge, predicted), mean_squared_error(df2.Discharge, predicted,squared = False))

[15.42130604  0.79623694  1.14121108  1.9158883   1.14121108  0.22984878
 19.26489873] -4.5223545100311 0.40639476389156404 125.8982317608141


In [19]:
r1 = linear_model.LinearRegression()
r1.fit(df1[["cluster(t-1)","cluster","RF101(t-1)","RF101(t-2)","RF117(t-1)","RF80(t-1)"]],df1.Discharge)
predicted = r1.predict(df2[["cluster(t-1)","cluster","RF101(t-1)","RF101(t-2)","RF117(t-1)","RF80(t-1)"]])
print(r1.coef_, r1.intercept_, r2_score(df2.Discharge, predicted), mean_squared_error(df2.Discharge, predicted,squared = False))

[18.07515547 18.98746475 -2.97017994  0.58212277  3.78620281  2.81808674] -3.7372468023594934 0.39647188935898114 126.94614598831356
